name: ProSeisSN
channels:
  - conda-forge
  - defaults
dependencies:
# python environment
  - pip
  - numpy
  - python
  - scipy
  - numba 
  - pathlib
  - pandas
  - ipython
  - ipywidgets
  - jupyterlab
  - jupyter
  - matplotlib
  - xarray
  - netcdf4
  - packaging
  - mpi4py
#
  - obspy
# spectral analysis using wavelets
  - pycwt
# Library to read and write ASDF files.
  - pyasdf
#
  - pygmt
  - cartopy
  - plotly
  - utm