name: ProSeisSN
channels:
  - conda-forge
  - defaults
dependencies:
# python environment
  - numpy
  - python
  - scipy
#  - numba  -> A compiler for Python with a collection of decorators.
  - obspy
  - pathlib
  - pandas
  - ipython
  - ipywidgets
  - jupyterlab
  - jupyter
  - pip
  - matplotlib
  - xarray
  - netcdf4
  - packaging
  - pygmt
  - pycwt
  - mpi4py
  - pyasdf
  - cartopy
  - plotly
  - utm
